---
title: "Why aRen't you using R foR youR statistical analyses and Reporting tasks?"
description: |
  A brief outline of some of the benefits of using R.
date: 04-24-2021
author:
  - first_name: Dan
    last_name: Burrell
    affiliation: University of Southern Queensland
    affiliation_url: https://usq.edu.au
    orcid_id: 0000-0002-9173-651X
preview: images/featured-useR.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: false
    code_folding: "View code"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Are you a biologist, still using inflexible, menu-driven statistics packages like SPSS or GenStat to produce randomization schemes for your experiments and to analyze your data using inflexible methods that may not be well suited to your needs? Then you need to learn R. 

# Why is R worth the effort?

Firstly, you should invest the effort to learn R because it is freely available and cross-platform (i.e. it works on Windows, Mac (OS-X), and Linux). This means that no matter where you are and who you collaborate with, you can easily share data, figures, analyses, and the code used to generate them. There are no expensive licenses with R. If you have previously had to update GenStat or SPSS licenses every year at what is sometimes a phenomenal cost to yourself or your workplace, you will already recognize the benefit of R being open-source (GPL) and completely free to download and use. It can save your current department or university or other institution a great deal of money, which they can then use to provide you with more opportunities elsewhere. Moreover, when you change workplaces R doesn;t become inaccessible, get lost, or become unusable. You can access and use R from anywhere in the world without cost. 

Secondly, R is an interpreted programming language. It does not involve extensive use of menus; you type commands instead. As a result, you have to know what to ask R, know why you're asking it, and know what to expect from R. You can't just click on menus and get some results. While this might seem like a lot of extra work, it means that by using R, you continually learn a great deal about statistics and data analysis. This also serves as a quality check on your analyses: you need to have a good grasp of the methods you're using to be able to ask R to use them and to be able to make good use of the output from R's built-in statistical functionality. This can only mean that your research skills will consistently improve and you will not seek to force "square peg" data in to a "round hole" statistical technique. After all, ANOVA is not the only statistical model in the world, and there is more to life than a t-test, or a table of mean rankings. 

Thirdly, R is extremely versatile and diverse. It can replace common combinations of programs that you might use in the process of analyzing your data. For example, In some analyses I have used two or three of Excel, SPSS, JASP, Stata, Minitab, SPSS, GenStat, Openings, JAGS and Stan, to name a few programs. Some of these involve costly licensing too, and they  produce results in software-specific files of various formats, all floating around in various spaces on your computer (or in hardcopy on your desk). Doing things this way means that you have a lot to keep track of to do the exploration, graphing and analysis that make up a given research project. Keeping a research project organized is hard enough without having to manage multiple files and file types, proprietary data formats, and the tools to put them all together. Furthermore, moving data between applications introduces extra steps into your workflow. And how much fun is it piecing all of this together 3 to 6 months after submitting a manuscript, and needing to make changes? These steps and frustrations are removed by investing in learning and using R. You can read in data files and output from a huge variety of other packages, and can even connect to other packages, like Python, Stan and JAGS, from within R, so you can keep all of your data and analysis code and outputs in one place.  This even more the case now, since the advent of RStudio and the project-driven workflow, Rmarkdown documents and knitr. R is now equipped with tools that enable you to keep everything in one place. Heck, even this blog --- all of it --- is created using R and RStudio and an R package called `distill`. 

Fourthly, R improves the (computational) reproducibility of your research. Reproducibility is all about being able to obtain consistent results using the same input data; computational steps, methods, and code; and conditions of analysis. If you've been paying attention in recent years you will have heard about the so-called reproducibility crisis in science. You will have seen open science promoted, along with pre-registration of experiments and other such things. Being able to maintain all of your work for a given experiment in a single R project, with its own local R environment and R package libraries frozen in time in the state they were in when you did the research, means that it is easy, even ten years down the track, to completely reproduce the exact analyses that you did originally at the touch of a button. This is hugely beneficial and in my opinion is one of the most important reasons why you should make the effort to learn R.  

Fifthly, R makes it easy to make outstanding publication-quality and publication-ready figures that can easily be exported in many different formats, including pdf. But now, with RStudio and Rmarkdown, you can write your entire scientific article in R, with the code embedded in code-chunks throughout the document. You can even publish whole books in R, using an R package called `bookdown`. Take a look at [these books](https://bookdown.org/home/archive/), for example.

Sixthly, R is now one of the most respected and most popular languages for statistics, graphics and programming in many areas of science, both within academia and outside (many large companies use R). There are a variety of reasons for this, including some of the things I've already mentioned, and also the fact that R is a product of the statistical community: it's core functionality (not to mention a wide array of its contributed packages) is written and maintained by statistical experts.  Knowing how to code your analyses using R is a sought after skill by many of your potential employers, and it will improve your CV. 

## Have I whet your appetite?

There are loads of resources online that will help you learn R from go to woe. For bite-sized chunks explained really clearly, I recommend beginning with the [MarinStatsLectures-R Programming & Statistics YouTube channel](https://www.youtube.com/c/marinstatlectures/featured).

If you prefer to work through a tutorial or workshop course, here is an [Introduction to R for Biologists](https://melbournebioinformatics.github.io/r-intro-biologists/intro_r_biologists.html). 

If you like to just read through a book, then for getting to know R, you can't really beat Hadley Wickham & Garrett Grolemund's [R for Data Science](https://r4ds.had.co.nz/) or Garrett Grolemund's [Hands-on Programming with R](https://rstudio-education.github.io/hopr/). Also, for a more statistically-oriented text, that uses R try Susan Holmes and Wolfgan Huber's [Modern Statistics for Modern Biology](https://web.stanford.edu/class/bios221/book/index.html).

All the best in your R learning journey! I promise you, you will not regret making the effort. 

